[package]
name = "infer"
version = "0.1.0"
edition = "2021"

[dependencies]
ort = "2.0.0-rc.11"
image = "0.25"
ndarray = { version = "0.16", features = ["rayon"] }
anyhow = "1.0"

[[bin]]
name = "infer"
path = "src/main.rs"